plugins {
    id 'groovy'
    id 'java'
    id 'application'
}

group 'pt.up.fe.ldts'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // Spock test dependencies
    testImplementation 'org.spockframework:spock-core:2.4-M1-groovy-4.0'

    testImplementation 'net.jqwik:jqwik:1.5.1'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

test {
    useJUnitPlatform {
        includeEngines ('junit-jupiter', 'jqwik')
    }
}

application {
    mainClass.set("Application")
}